<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : pl (OGame: pl)
 * Source   : resources/lang/en/t_overview.php
 * Built    : 2026-04-12T16:16:20+00:00
 */

return [
    'overview' => 'Podgląd',
    'temperature' => 'Temperatura',
    'position' => 'Pozycja',
];
