<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : ja (OGame: jp)
 * Source   : resources/lang/en/t_overview.php
 * Built    : 2026-04-12T13:09:51+00:00
 */

return [
    'overview' => '概要',
    'temperature' => '温度',
    'position' => '位置',
];
