<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : ro (OGame: ro)
 * Source   : resources/lang/en/t_overview.php
 * Built    : 2026-04-12T13:09:51+00:00
 */

return [
    'overview' => 'Vedere generala',
    'temperature' => 'Temperatură',
    'position' => 'Poziţie',
];
