<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hu (OGame: hu)
 * Source   : resources/lang/en/t_layout.php
 * Built    : 2026-04-12T13:09:51+00:00
 */

return [
    'player' => 'Játékos',
];
