<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hr (OGame: hr)
 * Source   : resources/lang/en/t_layout.php
 * Built    : 2026-04-12T16:16:20+00:00
 */

return [
    'player' => 'Igrač',
];
