<?php

use OGame\Enums\InventoryCategory;

/**
 * Registry of inventory item definitions.
 *
 * Keyed by a composite "item_type:tier" (tier = '' when not applicable).
 * Every auctioneer lot must resolve to a row here so wins can be stored.
 *
 * Fields:
 * - item_type           internal key (matches AuctionLotType value or custom)
 * - tier                nullable (bronze/silver/gold/platinum)
 * - category            InventoryCategory enum
 * - activation_type     instant | timed | permanent
 * - rarity              OGame rarity class (common/uncommon/rare/epic)
 * - image               /img/auctioneer/items/{family}_{tier}.png fallback chain
 * - title_key           t_shop_items.{key} lang key
 * - description_key     t_shop_items.{key} lang key
 * - duration_seconds    for timed items (0 = instant/permanent)
 * - payload_template    default payload data (overridden per-grant if needed)
 */
return [

    // ------- Time-reduction boosters (auctioneer-exclusive, one-shot) -------
    'booster_kraken:bronze'   => ['item_type' => 'booster_kraken',   'tier' => 'bronze',   'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'common',   'image' => 'kraken_bronze',   'title_key' => 'booster_kraken_title',   'description_key' => 'booster_kraken_desc',   'duration_seconds' => 0, 'payload_template' => ['reduction' => '30m']],
    'booster_kraken:silver'   => ['item_type' => 'booster_kraken',   'tier' => 'silver',   'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'uncommon', 'image' => 'kraken_silver',   'title_key' => 'booster_kraken_title',   'description_key' => 'booster_kraken_desc',   'duration_seconds' => 0, 'payload_template' => ['reduction' => '2h']],
    'booster_kraken:gold'     => ['item_type' => 'booster_kraken',   'tier' => 'gold',     'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'rare',     'image' => 'kraken_gold',     'title_key' => 'booster_kraken_title',   'description_key' => 'booster_kraken_desc',   'duration_seconds' => 0, 'payload_template' => ['reduction' => '6h']],
    'booster_kraken:platinum' => ['item_type' => 'booster_kraken',   'tier' => 'platinum', 'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'epic',     'image' => 'kraken_platinum', 'title_key' => 'booster_kraken_title',   'description_key' => 'booster_kraken_desc',   'duration_seconds' => 0, 'payload_template' => ['reduction' => '1d']],

    'booster_newtron:bronze'   => ['item_type' => 'booster_newtron', 'tier' => 'bronze',   'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'common',   'image' => 'newtron_bronze',   'title_key' => 'booster_newtron_title', 'description_key' => 'booster_newtron_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '30m']],
    'booster_newtron:silver'   => ['item_type' => 'booster_newtron', 'tier' => 'silver',   'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'uncommon', 'image' => 'newtron_silver',   'title_key' => 'booster_newtron_title', 'description_key' => 'booster_newtron_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '2h']],
    'booster_newtron:gold'     => ['item_type' => 'booster_newtron', 'tier' => 'gold',     'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'rare',     'image' => 'newtron_gold',     'title_key' => 'booster_newtron_title', 'description_key' => 'booster_newtron_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '6h']],
    'booster_newtron:platinum' => ['item_type' => 'booster_newtron', 'tier' => 'platinum', 'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'epic',     'image' => 'newtron_platinum', 'title_key' => 'booster_newtron_title', 'description_key' => 'booster_newtron_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '1d']],

    'booster_detroid:bronze'   => ['item_type' => 'booster_detroid', 'tier' => 'bronze',   'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'common',   'image' => 'detroid_bronze',   'title_key' => 'booster_detroid_title', 'description_key' => 'booster_detroid_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '30m']],
    'booster_detroid:silver'   => ['item_type' => 'booster_detroid', 'tier' => 'silver',   'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'uncommon', 'image' => 'detroid_silver',   'title_key' => 'booster_detroid_title', 'description_key' => 'booster_detroid_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '2h']],
    'booster_detroid:gold'     => ['item_type' => 'booster_detroid', 'tier' => 'gold',     'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'rare',     'image' => 'detroid_gold',     'title_key' => 'booster_detroid_title', 'description_key' => 'booster_detroid_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '6h']],
    'booster_detroid:platinum' => ['item_type' => 'booster_detroid', 'tier' => 'platinum', 'category' => InventoryCategory::Construction, 'activation_type' => 'instant', 'rarity' => 'epic',     'image' => 'detroid_platinum', 'title_key' => 'booster_detroid_title', 'description_key' => 'booster_detroid_desc', 'duration_seconds' => 0, 'payload_template' => ['reduction' => '1d']],

    // ------- Production amplifiers (1 week on activation) -------
    'amplifier_metal:bronze'       => ['item_type' => 'amplifier_metal',      'tier' => 'bronze',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'common',   'image' => 'amplifier_metal_bronze',       'title_key' => 'amplifier_metal_title',     'description_key' => 'amplifier_metal_desc',     'duration_seconds' => 604800, 'payload_template' => ['percent' => 10]],
    'amplifier_metal:silver'       => ['item_type' => 'amplifier_metal',      'tier' => 'silver',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'uncommon', 'image' => 'amplifier_metal_silver',       'title_key' => 'amplifier_metal_title',     'description_key' => 'amplifier_metal_desc',     'duration_seconds' => 604800, 'payload_template' => ['percent' => 20]],
    'amplifier_metal:gold'         => ['item_type' => 'amplifier_metal',      'tier' => 'gold',     'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'rare',     'image' => 'amplifier_metal_gold',         'title_key' => 'amplifier_metal_title',     'description_key' => 'amplifier_metal_desc',     'duration_seconds' => 604800, 'payload_template' => ['percent' => 30]],
    'amplifier_metal:platinum'     => ['item_type' => 'amplifier_metal',      'tier' => 'platinum', 'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'epic',     'image' => 'amplifier_metal_platinum',     'title_key' => 'amplifier_metal_title',     'description_key' => 'amplifier_metal_desc',     'duration_seconds' => 604800, 'payload_template' => ['percent' => 40]],

    'amplifier_crystal:bronze'     => ['item_type' => 'amplifier_crystal',    'tier' => 'bronze',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'common',   'image' => 'amplifier_crystal_bronze',     'title_key' => 'amplifier_crystal_title',   'description_key' => 'amplifier_crystal_desc',   'duration_seconds' => 604800, 'payload_template' => ['percent' => 10]],
    'amplifier_crystal:silver'     => ['item_type' => 'amplifier_crystal',    'tier' => 'silver',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'uncommon', 'image' => 'amplifier_crystal_silver',     'title_key' => 'amplifier_crystal_title',   'description_key' => 'amplifier_crystal_desc',   'duration_seconds' => 604800, 'payload_template' => ['percent' => 20]],
    'amplifier_crystal:gold'       => ['item_type' => 'amplifier_crystal',    'tier' => 'gold',     'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'rare',     'image' => 'amplifier_crystal_gold',       'title_key' => 'amplifier_crystal_title',   'description_key' => 'amplifier_crystal_desc',   'duration_seconds' => 604800, 'payload_template' => ['percent' => 30]],
    'amplifier_crystal:platinum'   => ['item_type' => 'amplifier_crystal',    'tier' => 'platinum', 'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'epic',     'image' => 'amplifier_crystal_platinum',   'title_key' => 'amplifier_crystal_title',   'description_key' => 'amplifier_crystal_desc',   'duration_seconds' => 604800, 'payload_template' => ['percent' => 40]],

    'amplifier_deuterium:bronze'   => ['item_type' => 'amplifier_deuterium',  'tier' => 'bronze',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'common',   'image' => 'amplifier_deuterium_bronze',   'title_key' => 'amplifier_deuterium_title', 'description_key' => 'amplifier_deuterium_desc', 'duration_seconds' => 604800, 'payload_template' => ['percent' => 10]],
    'amplifier_deuterium:silver'   => ['item_type' => 'amplifier_deuterium',  'tier' => 'silver',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'uncommon', 'image' => 'amplifier_deuterium_silver',   'title_key' => 'amplifier_deuterium_title', 'description_key' => 'amplifier_deuterium_desc', 'duration_seconds' => 604800, 'payload_template' => ['percent' => 20]],
    'amplifier_deuterium:gold'     => ['item_type' => 'amplifier_deuterium',  'tier' => 'gold',     'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'rare',     'image' => 'amplifier_deuterium_gold',     'title_key' => 'amplifier_deuterium_title', 'description_key' => 'amplifier_deuterium_desc', 'duration_seconds' => 604800, 'payload_template' => ['percent' => 30]],
    'amplifier_deuterium:platinum' => ['item_type' => 'amplifier_deuterium',  'tier' => 'platinum', 'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'epic',     'image' => 'amplifier_deuterium_platinum', 'title_key' => 'amplifier_deuterium_title', 'description_key' => 'amplifier_deuterium_desc', 'duration_seconds' => 604800, 'payload_template' => ['percent' => 40]],

    'amplifier_energy:bronze'      => ['item_type' => 'amplifier_energy',     'tier' => 'bronze',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'common',   'image' => 'amplifier_energy_bronze',      'title_key' => 'amplifier_energy_title',    'description_key' => 'amplifier_energy_desc',    'duration_seconds' => 604800, 'payload_template' => ['percent' => 10]],
    'amplifier_energy:silver'      => ['item_type' => 'amplifier_energy',     'tier' => 'silver',   'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'uncommon', 'image' => 'amplifier_energy_silver',      'title_key' => 'amplifier_energy_title',    'description_key' => 'amplifier_energy_desc',    'duration_seconds' => 604800, 'payload_template' => ['percent' => 20]],
    'amplifier_energy:gold'        => ['item_type' => 'amplifier_energy',     'tier' => 'gold',     'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'rare',     'image' => 'amplifier_energy_gold',        'title_key' => 'amplifier_energy_title',    'description_key' => 'amplifier_energy_desc',    'duration_seconds' => 604800, 'payload_template' => ['percent' => 30]],
    'amplifier_energy:platinum'    => ['item_type' => 'amplifier_energy',     'tier' => 'platinum', 'category' => InventoryCategory::Resources, 'activation_type' => 'timed', 'rarity' => 'epic',     'image' => 'amplifier_energy_platinum',    'title_key' => 'amplifier_energy_title',    'description_key' => 'amplifier_energy_desc',    'duration_seconds' => 604800, 'payload_template' => ['percent' => 40]],

    // ------- Resource lot (auctioneer "resources" fixed amounts) -------
    'resources_lot:bronze'   => ['item_type' => 'resources_lot', 'tier' => 'bronze',   'category' => InventoryCategory::Resources, 'activation_type' => 'instant', 'rarity' => 'common',   'image' => 'resources_lot_bronze',   'title_key' => 'resources_lot_title', 'description_key' => 'resources_lot_desc', 'duration_seconds' => 0, 'payload_template' => []],
    'resources_lot:silver'   => ['item_type' => 'resources_lot', 'tier' => 'silver',   'category' => InventoryCategory::Resources, 'activation_type' => 'instant', 'rarity' => 'uncommon', 'image' => 'resources_lot_silver',   'title_key' => 'resources_lot_title', 'description_key' => 'resources_lot_desc', 'duration_seconds' => 0, 'payload_template' => []],
    'resources_lot:gold'     => ['item_type' => 'resources_lot', 'tier' => 'gold',     'category' => InventoryCategory::Resources, 'activation_type' => 'instant', 'rarity' => 'rare',     'image' => 'resources_lot_gold',     'title_key' => 'resources_lot_title', 'description_key' => 'resources_lot_desc', 'duration_seconds' => 0, 'payload_template' => []],
    'resources_lot:platinum' => ['item_type' => 'resources_lot', 'tier' => 'platinum', 'category' => InventoryCategory::Resources, 'activation_type' => 'instant', 'rarity' => 'epic',     'image' => 'resources_lot_platinum', 'title_key' => 'resources_lot_title', 'description_key' => 'resources_lot_desc', 'duration_seconds' => 0, 'payload_template' => []],
];
