<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : cs (OGame: cz)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T13:09:51+00:00
 */

return [
    'metal_mine' => [
        'title' => 'Důl na Kov',
        'description' => 'V těchto dolech se těží rudy rozličných kovů. Ta se potom zušlechťuje na materiály, které jsou nejdůležitějšími surovinami pro všechna vznikající i zavedená impéria.',
        'description_long' => 'Kov je primární surovina používaná ke konstrukci lodí a budov. Protože je kov nejhojnější ze všech surovin, jeho obchodní cena je z nich považována za nejnižší. Produkce stoupá, když doly dosáhnou větších hloubek, nicméně práce v těchto obrovských hloubkách si žádá zvýšení příkonu energie.',
    ],
    'crystal_mine' => [
        'title' => 'Důl na krystaly',
        'description' => 'Krystaly jsou hlavní surovinou používanou na výrobu elektrických obvodů a určitých slitinových směsí.',
        'description_long' => 'Doly na krystaly poskytují hlavní surovinu používanou na výrobu elektrických obvodů a určitých slitinových směsí. Těžba krystalů spotřebovává zhruba 1,5krát více energie než těžba kovu, což dělá krystaly hodnotnějšími. Téměř veškeré lodě a budovy vyžadují krystaly. Většina krystalů vyžadovaných ke stavbě vesmírných lodí je ale velmi vzácná a stejně jako kov je možné je nalézt pouze v určité hloubce. Proto stavba dolů v hlubších vrstvách zvyšuje množství vyprodukovaných krystalů.',
    ],
    'deuterium_synthesizer' => [
        'title' => 'Syntetizér deuteria',
        'description' => 'Syntetizér deuteria vytahuje stopové množství deuteria z vody na planetě.',
        'description_long' => 'Deuteriu se také říká těžký vodík. Jedná se o stabilní izotop vodíku, který se v přírodě vyskytuje pouze v oceánech, a to v koloniích, kdy na jeden atom deuteria připadá 6500 atomů vodíku (~154 PPM). Deuterium je tedy zastoupeno pouze ve množství 0,015 % (na základě váhy 0,030 %) z celkového objemu veškeré vody. Deuterium se zpracovává pomocí speciálních syntetizérů, které mají pomocí speciálně navržených odstředivek schopnost jej oddělit od zbytku vody. Vylepšení syntetizéru deuteria umožňuje zvýšit množství deuteria, které bude syntetizováno. Deuterium se používá při snímání senzorů falangy, prohlížení galaxií, jako palivo pro lodě a také při provádění specializovaných výzkumů.',
    ],
    'solar_plant' => [
        'title' => 'Solární elektrárna',
        'description' => 'Solární elektrárny vstřebávají energii ze slunečního záření. Všechny doly potřebují energii, aby správně fungovaly.',
        'description_long' => 'Gigantické solární elektárny jsou používány pro výrobu energie pro doly a syntetizátor deuteria. Jakmile je solární elektrárna vylepšena, povrchová plocha fotočlánků, pokrývajících planetu, se zvýší, což má za důsledek vyšší výkon. Solární elektrárny reprezentují základ planetárního zásobování energií.',
    ],
    'fusion_plant' => [
        'title' => 'Fúzní reaktor',
        'description' => 'Fúzní reaktor využívá deuteria k výrobě energie.',
        'description_long' => 'Ve fúzních elektrárnách se jádra vodíku za obrovské teploty a tlaku slučují do jader helia, přičemž se uvolňuje obrovské množství energie. Na každý gram spotřebovaného deuteria lze vyrobit až 41,32*10^-13 Joule energie; s 1 g jste schopni vyrobit 172 MWh energie. 

Větší reaktorové komplexy využívají více deuteria a mohou produkovat více energie za hodinu. Energetický efekt by mohl být zvýšen výzkumem energetických technologií. 

Výroba energie ve fúzním zařízení se vypočítá takto: 
30 * [Level Fusion Plant] * (1,05 + [Level Energy Technology] * 0,01) ^ [Level Fusion Plant]',
    ],
    'metal_store' => [
        'title' => 'Sklad kovu',
        'description' => 'Poskytuje uskladnění pro čerstvě natěžený kov.',
        'description_long' => 'Toto obří skladiště slouží ke skladování kovové rudy. Každá úroveň vylepšení zvyšuje množství kovové rudy, kterou lze uložit. Pokud budou obchody plné, další kov se těžit nebude. 

Sklad kovů chrání určité procento denní produkce dolu (max. 10 procent).',
    ],
    'crystal_store' => [
        'title' => 'Sklad krystalu',
        'description' => 'Poskytuje uskladnění pro přebytečný krystal.',
        'description_long' => 'Nezpracovaný krystal bude mezitím uložen v těchto obřích skladovacích halách. S každou úrovní upgradu se zvyšuje množství krystalů, které lze uložit. Pokud jsou sklady krystalů plné, nebude se těžit žádný další krystal. 

Úložiště krystalů chrání určité procento denní produkce dolu (max. 10 procent).',
    ],
    'deuterium_store' => [
        'title' => 'Nádrž na deuterium',
        'description' => 'Obrovské nádrže pro skladování čerstvě syntetizovaného deuteria.',
        'description_long' => 'Nádrž na deuterium je určena pro skladování nově syntetizovaného deuteria. Jakmile je zpracován syntezátorem, je veden do této nádrže pro pozdější použití. S každým upgradem nádrže se celková skladovací kapacita zvyšuje. Po dosažení kapacity již nebude syntetizováno žádné další deuterium. 

Deuterium Tank chrání určité procento denní produkce syntezátoru (max. 10 procent).',
    ],
    'robot_factory' => [
        'title' => 'Továrna na roboty',
        'description' => 'Továrny na roboty poskytují robokonstruktéry na pomoc při stavbách budov. Každá úroveň zvyšuje rychlost vylepšování budov.',
        'description_long' => 'Továrny na roboty produkují roboty, kteří jsou používáni při stavbách a vylepšováních budov. Každé vylepšení továrny na roboty zvyšuje počet a výkonnost jednotek robotů použitých pro konstrukci budovy, což snižuje čas potřebný na stavbu.',
    ],
    'shipyard' => [
        'title' => 'Hangár',
        'description' => 'V hangáru jsou stavěny veškeré typy lodí a obranných zařízení.',
        'description_long' => '行星造船廠是負責宇宙飛船以及防禦設施的建造的.當造船廠升級後,它將以更高的生産效率來建造更多種類的艦船.一旦行星上的奈米機器人工廠落成,艦船的建造速度將會得到飛速提昇.',
    ],
    'research_lab' => [
        'title' => 'Výzkumná laboratoř',
        'description' => 'Výzkumná laboratoř je nezbytná ke zkoumání nových technologií.',
        'description_long' => '研究實驗室是任何帝國都必不可少的一個重要組成,在那裡您可以發現新科技以及將舊有科技加以升級.每升一級研究實驗室,研發新技術的效率速度將大大提昇,同時也解鎖某些新科技的研究限制.為了能盡可能快地完成研究,研究實驗室的科學家們應該被立即部署到新殖民地展開工作和開發.這樣,新科技的知識就可以很快地傳播到整個帝國.',
    ],
    'alliance_depot' => [
        'title' => 'Alianční sklad',
        'description' => 'Alianční sklad dodává palivo spřáteleným letkám, pomáhajícím s obranou v orbitě.',
        'description_long' => '聯盟太空站為軌道內協助防禦的友好艦隊提供燃料補給.聯盟太空站每升一級,將可以每小時為軌道內的艦隊提供特殊的重氫燃料補給.',
    ],
    'missile_silo' => [
        'title' => 'Raketové silo',
        'description' => 'Raketová sila se používají k uschování raket.',
        'description_long' => '在21世紀發生的全面核戰爭摧毀了地球本身,但就科技而言,在宇宙中依然需要這個恐怖的武器的存在.科學家十分擔憂被無賴恐怖組織掌控核彈轟炸.所以他們決定使用同樣的彈道技術製造了一個截然相反的制衡武器抵禦恐怖襲擊.導彈發射井是用來建造,儲藏及發射星際導彈和反彈道導彈的設施.每一級導彈發射井可以儲存5枚星際導彈或10枚反彈道導彈. 導彈是可以混合儲存的; 一枚星際導彈所需的空間可以放置兩枚反彈道導彈.',
    ],
    'nano_factory' => [
        'title' => 'Továrna s nanoboty',
        'description' => 'Toto je ultimátní robotechnologie. Každá úroveň krátí čas výstavby budov, lodí a obranných konstrukcí.',
        'description_long' => '奈米機器人,也被稱作奈米微粒,是一種機械與電力混合驅動的裝置,其測量尺寸單位為奈米(百萬分之一毫米,或單位:10^-9米).奈米機器人精密而微小的尺寸將轉化提高工序速度效率.該工廠生産的奈米機器人,是採用了最尖端的終極機械人技術.一旦建成,每級奈米機器人工廠都將大幅顯著地減少建築物,艦船以及防禦設施的建造時間.',
    ],
    'terraformer' => [
        'title' => 'Terraformer',
        'description' => 'Terraformer zvyšuje množství použitelného povrchu planety.',
        'description_long' => 'S přibývající výstavbou na planetách je i životní prostor pro kolonii stále více a více omezený. Tradiční metody, jako jsou výškové a podzemní stavby, jsou stále nedostačující. Malá skupina vysokoenergetických fyziků a nanoinženýrů nakonec dospěla k řešení: terraforming. 
Terraformer s využitím obrovského množství energie dokáže obdělávat celé plochy země nebo dokonce kontinenty. V této budově se nachází výroba nanitů vytvořených speciálně pro tento účel, které zajišťují konzistentní kvalitu půdy. 

Každá úroveň terraformeru umožňuje obdělávat 5 polí. S každou úrovní zabírá terraformer jedno pole sám. Každé 2 úrovně terraformeru obdržíte 1 bonusové pole. 

Jakmile je terraformer postaven, nelze jej demontovat.',
    ],
    'space_dock' => [
        'title' => 'Vesmírný dok',
        'description' => 'Ve vesmírném doku lze opravovat vraky lodí.',
        'description_long' => 'Space Dock nabízí možnost opravit lodě zničené v bitvě, které po sobě zanechaly trosky. Doba opravy trvá maximálně 12 hodin, ale trvá minimálně 30 minut, než bude možné lodě znovu uvést do provozu. 

Opravy musí začít do 3 dnů od vytvoření vraku. Opravené lodě musí být po dokončení oprav vráceny do služby ručně. Pokud tak neučiníte, jednotlivé lodě jakéhokoli typu budou vráceny do provozu po 3 dnech. 

Vrak se objeví pouze v případě, že bylo zničeno více než 150 000 jednotek včetně vlastních lodí, které se zúčastnily boje s hodnotou alespoň 5 % lodních bodů. 

Protože Space Dock pluje na oběžné dráze, nevyžaduje planetární pole.',
    ],
    'lunar_base' => [
        'title' => 'Základna na měsíci',
        'description' => 'Vzhledem k tomu, že Měsíc nemá atmosféru, je k vytvoření obyvatelného prostoru zapotřebí měsíční základna.',
        'description_long' => 'Měsíc nemá atmosféru, takže před založením osady musí být nejprve postavena měsíční základna. To pak poskytuje kyslík, ohřev a gravitaci. S každou vybudovanou úrovní je v biosféře poskytnuta větší obytná a rozvojová oblast. Každá postavená úroveň umožňuje tři pole pro další budovy. S každou úrovní zabírá lunární základna sama jedno pole. 
Jakmile je měsíční základna postavena, nelze ji strhnout.',
    ],
    'sensor_phalanx' => [
        'title' => 'Senzor falangy',
        'description' => 'Pomocí senzorové falangy lze objevit a pozorovat flotily jiných říší. Čím větší je pole senzorové falangy, tím větší dosah může snímat.',
        'description_long' => 'Pomocí senzorů s vysokým rozlišením Sensor Phalanx nejprve skenuje spektrum světla, složení plynů a záření ze vzdáleného světa a přenáší data do superpočítače ke zpracování. Jakmile jsou informace získány, superpočítač porovnává změny ve spektru, složení plynu a radiačních emisích se základní linií známých změn spektra vytvořených různými pohyby lodí. Výsledná data pak zobrazují aktivitu jakékoli flotily v dosahu falangy. Aby se zabránilo přehřátí superpočítače během procesu, je chlazen použitím 5k zpracovaného deuteria. 
Chcete-li použít Phalanx, klikněte na libovolnou planetu v zobrazení galaxie v dosahu vašich senzorů.',
    ],
    'jump_gate' => [
        'title' => 'Hyperprostorová brána',
        'description' => 'Skokové brány jsou obrovské transceivery schopné poslat i tu největší flotilu během okamžiku ke vzdálené skokové bráně.',
        'description_long' => 'Skoková brána je systém obřích vysílačů/přijímačů schopných vyslat i ty největší flotily k přijímací bráně kdekoli ve vesmíru bez ztráty času. Využitím technologie podobné technologii červí díry k dosažení skoku není potřeba deuterium. Mezi skoky musí uplynout doba nabíjení v délce několika minut, aby se umožnila regenerace. Není možná ani přeprava surovin přes bránu. S každou úrovní vylepšení lze zkrátit dobu ochlazení skokové brány.',
    ],
    'energy_technology' => [
        'title' => 'Energetická technologie',
        'description' => 'Znalost různých druhů energie je nezbytná pro mnoho nových technologií.',
        'description_long' => 'Jak různé oblasti výzkumu pokročily, bylo zjištěno, že současná technologie distribuce energie nestačí k zahájení určitého specializovaného výzkumu. S každým vylepšením vaší energetické technologie lze provést nový výzkum, který odemkne vývoj důmyslnějších lodí a obrany.',
    ],
    'laser_technology' => [
        'title' => 'Laserová technologie',
        'description' => 'Zaostřování světla produkuje paprsek který způsobuje poškození při zásahu objektu.',
        'description_long' => 'Lasery (zesílení světla stimulovanou emisí záření) produkují intenzivní, energeticky bohatou emisi koherentního světla. Tato zařízení lze použít v nejrůznějších oblastech, od optických počítačů až po těžké laserové zbraně, které bez námahy proříznou pancéřovou technologii. Laserová technologie poskytuje důležitý základ pro výzkum dalších zbraňových technologií.',
    ],
    'ion_technology' => [
        'title' => 'Iontová technologie',
        'description' => 'Koncentrace iontů ti umožní postavit kanóny, které mohou způsobit nesmírné škody. Každá úroveň také sníží náklady na zbourání budovy o 4 %.',
        'description_long' => 'Ionty mohou být koncentrovány a urychlovány do smrtícího paprsku. Tyto paprsky pak mohou způsobit obrovské škody. Naši vědci také vyvinuli techniku, která jednoznačně sníží náklady na dekonstrukci budov a systémů. Pro každou úroveň výzkumu se náklady na dekonstrukci sníží o 4 %.',
    ],
    'hyperspace_technology' => [
        'title' => 'Hyperprostorová technologie',
        'description' => 'Integrací 4. a 5. dimenze je nyní možné zkoumat nový druh pohonu, který je ekonomičtější a efektivnější.',
        'description_long' => 'Teoreticky se myšlenka cestování hyperprostorem opírá o existenci samostatné a sousední dimenze. Když je aktivován, hyperprostorový pohon přesune hvězdnou loď do této jiné dimenze, kde může překonat obrovské vzdálenosti za dobu značně zkrácenou oproti době, kterou by zabrala v "normálním" prostoru. Jakmile dosáhne bodu v hyperprostoru, který odpovídá jeho cíli v reálném prostoru, znovu se vynoří. 
Jakmile je prozkoumána dostatečná úroveň hyperprostorové technologie, hyperprostorový pohon již není jen teorií. Každé vylepšení tohoto pohonu zvyšuje nosnost vašich lodí o 5 % základní hodnoty.',
    ],
    'plasma_technology' => [
        'title' => 'Plasmová technologie',
        'description' => 'Další vývoj iontové technologie urychluje vysokoenergetické plazma, které tak dosahuje devastačních škod a navíc optimalizuje produkci kovu a krystalu (1 %/0,66 %/0,33 % za úroveň).',
        'description_long' => 'Další vývoj iontové technologie, která nezrychluje ionty, ale místo toho vysokoenergetické plazma, které pak může způsobit zničující poškození při dopadu na předmět. Naši vědci také našli způsob, jak pomocí této technologie znatelně zlepšit těžbu kovů a krystalů. 

Výroba kovů se zvyšuje o 1 %, produkce krystalů o 0,66 % a produkce deuteria o 0,33 % na konstrukční úroveň plazmové technologie.',
    ],
    'combustion_drive' => [
        'title' => 'Spalovací pohon',
        'description' => 'Rozvoj tohoto pohonu některé lodě zrychlí, i když každá úroveň zvýší jejich rychlost pouze o 10 % ze základní hodnoty.',
        'description_long' => 'Combustion Drive je nejstarší z technologií, ale stále se používá. U spalovacího pohonu se výfuk tvoří z pohonných látek nesených v lodi před použitím. V uzavřené komoře jsou tlaky v každém směru stejné a nedochází k žádnému zrychlení. Pokud je na dně komory vytvořen otvor, pak již na této straně tlak nepůsobí. Zbývající tlak dává výsledný tah na straně protilehlé k otvoru, který pohání loď vpřed vytlačováním výfukových plynů dozadu extrémně vysokou rychlostí. 

S každou úrovní vyvinutého Combustion Drive se rychlost malých a velkých nákladních lodí, lehkých stíhaček, recyklátorů a špionážních sond zvyšuje o 10 %.',
    ],
    'impulse_drive' => [
        'title' => 'Impulzní pohon',
        'description' => 'Impulzní pohon je založen na principu reakce. Další vývoj tohoto pohonu činí některé lodě rychlejšími, ačkoliv každá úroveň pouze zvyšuje rychlost o 20% ze základní hodnoty.',
        'description_long' => 'Impulsní pohon je založen na principu zpětného rázu, při kterém je stimulovaná emise záření produkována převážně jako odpadní produkt jaderné fúze za účelem získání energie. Kromě toho mohou být injektovány další hmoty. S každou vyvinutou úrovní Impulsního pohonu se rychlost bombardérů, křižníků, těžkých stíhaček a koloniálních lodí zvyšuje o 20 % základní hodnoty. Kromě toho jsou malé transportéry vybaveny impulsními pohony, jakmile jejich úroveň výzkumu dosáhne 5. Jakmile výzkum Impulsního pohonu dosáhne úrovně 17, recyklátory jsou znovu vybaveny impulsními pohony. 

Meziplanetární střely také cestují dále s každou úrovní.',
    ],
    'hyperspace_drive' => [
        'title' => 'Hyperprostorový pohon',
        'description' => 'Hyperprostorový pohon deformuje vesmír okolo lodi. Rozvoj tohoto pohonu činí některé lodě rychlejšími, ačkoliv každá úroveň pouze zvyšuje rychlost o 30 % ze základní hodnoty.',
        'description_long' => 'V bezprostřední blízkosti lodi je prostor pokřivený, takže lze velmi rychle překonat velké vzdálenosti. Čím více je Hyperprostorový pohon vyvinut, tím silnější je pokřivená povaha prostoru, přičemž rychlost lodí, které jsou jím vybaveny (Bojové křižníky, Bitevní lodě, Torpédoborce, Hvězdy smrti, Pathfinders a Reapery) se zvyšuje o 30 % na úroveň. Kromě toho je bombardér postaven s Hyperprostorovým pohonem, jakmile výzkum dosáhne úrovně 8. Jakmile výzkum Hyperprostorového pohonu dosáhne úrovně 15, je Recycler znovu vybaven Hyperprostorovým pohonem.',
    ],
    'espionage_technology' => [
        'title' => 'Špionážní technologie',
        'description' => 'Informace o ostatních planetách a měsících můžeš získat použitím této technologie.',
        'description_long' => '間諜探測技術是提高感測器的增幅技術.這項技術的等級越高,就能獲得其它帝國更多的活動訊息.
間諜衛星探測資料的多寡,主要取決於自己和對手的間諜技術的差距.自己的技術等級越高,就能獲得更多資料且被發現的機率也越低.在同一任務中發送的間諜衛星越多,就能回傳更多訊息-但此舉也大大提高了被發現的機率.
提昇間諜探測技術也可以得知關於接近自己行星的艦隊資料:
-等級2可以看到艦隊總數和正常攻擊的通知
-等級4可以區分出艦隊內有哪些種類的船艦
-等級8可以分辨各種船艦各有幾艘.
對即將到來的攻擊來說,這項技術是不可或缺的.它能有效告知你的艦隊有否必要作出無謂的犧牲.這正是為何越早研究該技術越有利的原因.',
    ],
    'computer_technology' => [
        'title' => 'Počítačová technologie',
        'description' => 'Se zvyšováním kapacity tvých počítačů můžeš ovládat více letek. Každý úroveň počítačové technologie zvyšuje maximální počet letek o jednu.',
        'description_long' => '從艦隊執行任何一項任務開始,艦隊就由來自出發行星上的一系列電腦系統控制.這些複雜龐大的電腦精準地運算著抵達時間,軌道運算,監測調節飛行速度,以及在有必要時做出相關訂正.每提昇1級電腦技術科技,戰鬥電腦將獲得升級從而獲得額外可管理的1個艦隊指揮權.電腦科技應該在您的帝國各處研究實驗室中持續不斷地加以深入研究.',
    ],
    'astrophysics' => [
        'title' => 'Astrofyzika',
        'description' => 'S astrofyzikálním výzkumným modulem mohou lodě podnikat dlouhé expedice. Za každé 2 úrovně této technologie můžeš obsadit další planetu.',
        'description_long' => 'Další poznatky v oblasti astrofyziky umožňují stavbu laboratoří, které lze osadit na další a další lodě. To umožňuje dlouhé expedice daleko do neprobádaných oblastí vesmíru. Kromě toho lze tyto pokroky použít k další kolonizaci vesmíru. Pro každé dvě úrovně této technologie lze použít další planetu.',
    ],
    'intergalactic_research_network' => [
        'title' => 'Intergalaktická výzkumná síť',
        'description' => 'Výzkumníci na různých planetách komunikují pomocí této sítě.',
        'description_long' => 'Toto je vaše síť hlubokého vesmíru, která sděluje výsledky výzkumu vašim koloniím. S IRN lze dosáhnout rychlejších časů výzkumu propojením výzkumných laboratoří nejvyšší úrovně na úrovni vyvinuté IRN. 
Aby každá kolonie fungovala, musí být schopna provádět výzkum samostatně.',
    ],
    'graviton_technology' => [
        'title' => 'Gravitonová technologie',
        'description' => 'Vystřelení koncentrovaného paprsku gravitonových částic může vytvořit umělé gravitační pole, které může zničit lodě nebo dokonce měsíce.',
        'description_long' => 'Graviton je elementární částice, která je bez hmotnosti a nemá žádný náklad. Určuje gravitační sílu. Odpálením koncentrovaného nákladu gravitonů lze zkonstruovat umělé gravitační pole. Na rozdíl od černé díry do sebe vtahuje hmotu. Tak může zničit lodě a dokonce celé měsíce. K výrobě dostatečného množství gravitonů je zapotřebí obrovské množství energie. Ke konstrukci ničivé Hvězdy smrti je nutný výzkum Graviton.',
    ],
    'weapon_technology' => [
        'title' => 'Technologie zbraní',
        'description' => 'Zbraňové systémy činí zbraňové vybavení výkonnějším. Každá úroveň zbraňových systémů zvyšuje sílu zbraní jednotek o 10% ze základní hodnoty.',
        'description_long' => '武器技術研究是科技研究的關鍵,並且在您對抗敵國時,是至關重要的生存關鍵.每項完成的武器技術等級研究,艦船及您的防禦設施的武器系統將得到效果提昇.每提昇一級都將加強您的武器基礎數值的10%.',
    ],
    'shielding_technology' => [
        'title' => 'Technologie štítu',
        'description' => 'Díky technologii štítů jsou štíty na lodích a obranných zařízeních efektivnější. Každá úroveň technologie štítů zvyšuje sílu štítů o 10 % základní hodnoty.',
        'description_long' => '隨著電磁層發生器的發明,科學家瞭解到,可以製作一個人造的護盾來保護太空船的船員避開太空太陽輻射的惡劣環境,同時也能為艦船在遭遇敵人攻擊時提供保護作用.就在科學家最終完善了該技術後,電磁層發生器就被安裝到所有的艦船及防禦設施上去了.每提昇一級護盾技術,電磁層發生器亦將獲得升級並增加10%的基礎護盾強度.',
    ],
    'armor_technology' => [
        'title' => 'Pancéřování',
        'description' => 'Speciální slitiny zdokonalují obrnění na lodích a obranných stavbách. Efektivita obrnění může být zvýšena o 10% za úroveň.',
        'description_long' => 'Prostředí hlubokého vesmíru je drsné. Piloti a posádka na různých misích čelili nejen intenzivnímu slunečnímu záření, ale čelili také vyhlídce na zasažení vesmírným odpadem nebo zničení nepřátelskou palbou při útoku. Díky objevu slitiny karbidu hliníku a lithia a karbidu titanu, u níž bylo zjištěno, že je lehká a odolná, to posádce poskytlo určitý stupeň ochrany. S každou vyvinutou úrovní Armor Technology se vyrábí kvalitnější slitina, která zvyšuje pevnost pancíře o 10 %.',
    ],
    'small_cargo' => [
        'title' => 'Malý transportér',
        'description' => 'Malý transportér je hbitá loď, která je schopna rychle transportovat suroviny na jiné planety.',
        'description_long' => 'Transportéry jsou velké asi jako stíhačky, přesto se vzdávají vysoce výkonných pohonů a palubních zbraní, aby zvýšily svou přepravní kapacitu. V důsledku toho by měl být transportér vyslán do bitev pouze tehdy, když je doprovázen bojovými loděmi. 

Jakmile Impulsní pohon dosáhne úrovně výzkumu 5, malý transportér jede zvýšenou základní rychlostí a je vybaven impulsním pohonem.',
    ],
    'large_cargo' => [
        'title' => 'Velký transportér',
        'description' => 'Tento transportér má mnohem větší nákladovou kapacitu než malý transportér a je zpravidla rychlejší díky vylepšenému pohonu.',
        'description_long' => 'Jak se čas vyvíjel, nájezdy na kolonie vedly k zachycení většího a většího množství zdrojů. V důsledku toho byly malé náklady posílány ve velkém množství, aby kompenzovaly větší zajetí. Rychle se zjistilo, že je potřeba nová třída lodí, aby se maximalizovaly zdroje zachycené při nájezdech, ale zároveň byly nákladově efektivní. Po dlouhém vývoji se zrodil Large Cargo. 

Aby se maximalizovaly zdroje, které lze uložit v nákladových prostorech, má tato loď jen málo zbraní nebo brnění. Díky instalovanému vysoce vyvinutému spalovacímu motoru slouží jako nejúspornější dodavatel zdrojů mezi planetami a nejúčinnější při nájezdech na nepřátelské světy.',
    ],
    'colony_ship' => [
        'title' => 'Kolonizační loď',
        'description' => 'S touto lodí můžeš kolonizovat volné planety.',
        'description_long' => 'Ve 20. století se Člověk rozhodl jít za hvězdami. Nejprve to bylo přistání na Měsíci. Poté byla postavena vesmírná stanice. Mars byl kolonizován brzy poté. Brzy se zjistilo, že náš růst závisí na kolonizaci jiných světů. Vědci a inženýři z celého světa se shromáždili, aby vyvinuli největší úspěch všech lidí. Zrodila se koloniální loď. 

Tato loď slouží k přípravě nově objevené planety na kolonizaci. Jakmile dorazí do cíle, loď se okamžitě promění v obvyklý životní prostor, který pomáhá při zalidňování a těžbě nového světa. Maximální počet planet je tak určen pokrokem v astrofyzickém výzkumu. Dvě nové úrovně astrotechnologie umožňují kolonizaci jedné další planety.',
    ],
    'recycler' => [
        'title' => 'Recyklátor',
        'description' => 'Recyklátory jsou jediné lodě schopné po boji sklízet pole trosek plovoucích na oběžné dráze planety.',
        'description_long' => 'Boj ve vesmíru nabýval stále větších rozměrů. Tisíce lodí byly zničeny a zdroje jejich pozůstatků se zdály být navždy ztraceny v polích trosek. Normální nákladní lodě se nemohly dostat dostatečně blízko k těmto polím, aniž by riskovaly značné poškození. 
Nedávný vývoj technologií štítů tento problém účinně obešel. Byla vytvořena nová třída lodí, které byly podobné Transportérům: Recyclers. Jejich úsilí pomohlo shromáždit myšlenkově ztracené zdroje a poté je zachránit. Trosky už díky novým štítům nepředstavovaly žádné skutečné nebezpečí. 

Jakmile výzkum Impulsního pohonu dosáhne úrovně 17, Recyclers jsou znovu vybaveny Impulsními pohony. Jakmile výzkum Hyperprostorového pohonu dosáhne úrovně 15, Recyclery jsou znovu vybaveny Hyperprostorovými pohony.',
    ],
    'espionage_probe' => [
        'title' => 'Špionážní sonda',
        'description' => 'Špionážní sondy jsou malé, hbité letouny, které poskytují data o letkách a planetách na obrovské vzdálenosti.',
        'description_long' => 'Špionážní sondy jsou malé, obratné drony, které poskytují data o flotilách a planetách. Je vybaven speciálně navrženými motory a umožňuje jim překonat obrovské vzdálenosti během několika minut. Jakmile jsou na oběžné dráze kolem cílové planety, rychle shromažďují data a předávají zprávu zpět prostřednictvím vaší sítě Deep Space Network k vyhodnocení. Existuje však riziko pro aspekt inteligentního shromažďování. Během doby, kdy je zpráva přenášena zpět do vaší sítě, může být signál detekován cílem a sondy mohou být zničeny.',
    ],
    'solar_satellite' => [
        'title' => 'Solární satelit',
        'description' => 'Solární satelity jsou jednoduché platformy solárních článků, které se nacházejí na vysoké, stacionární oběžné dráze. Shromažďují sluneční světlo a přenášejí je na pozemní stanici pomocí laseru.',
        'description_long' => 'Vědci objevili způsob přenosu elektrické energie do kolonie pomocí speciálně navržených satelitů na geosynchronní oběžné dráze. Solární družice shromažďují sluneční energii a přenášejí ji na pozemní stanici pomocí pokročilé laserové technologie. Účinnost sluneční družice závisí na síle slunečního záření, které přijímá. V zásadě je produkce energie na drahách blíže Slunci větší než na planetách na drahách vzdálených od Slunce. 
Díky svému dobrému poměru cena/výkon mohou solární satelity vyřešit mnoho energetických problémů. Ale pozor: Sluneční satelity lze v bitvě snadno zničit.',
    ],
    'crawler' => [
        'title' => 'Crawler',
        'description' => 'Crawler zvyšuje produkci kovu, krystalu a deuteria o 0,02 %, 0,02 % a 0,02 %. Jako sběrateli se ti rovněž zvýší produkce. Maximální celkový bonus záleží na úrovni tvých dolů.',
        'description_long' => 'Crawler je velké zákopové vozidlo, které zvyšuje produkci dolů a syntetizérů. Je hbitější než vypadá, ale není moc silný. Každý crawler zvyšuje produkci kovu o 0,02 %, krystalu o 0,02 % a deuteria o 0,02 %. Jako sběrateli se ti rovněž zvýší produkce. Maximální celkový bonus záleží na úrovni tvých dolů.',
    ],
    'pathfinder' => [
        'title' => 'Průzkumník',
        'description' => 'Pathfinder je rychlá a obratná loď, určená pro výpravy do neznámých sektorů vesmíru.',
        'description_long' => 'Pathfinder je nejnovější vývoj v technologii průzkumu. Tato loď byla speciálně navržena pro členy třídy Discoverer s cílem maximalizovat jejich potenciál. Pathfinder, vybavený pokročilými skenovacími systémy a velkým nákladovým prostorem pro záchranu zdrojů, vyniká při expedicích. Jeho sofistikované senzory dokážou detekovat cenné zdroje a anomálie, které by ostatní lodě nepostřehly. Loď kombinuje vysokou rychlost s dobrou kapacitou nákladu, takže je ideální pro rychlé průzkumné mise a shromažďování zdrojů ze vzdálených sektorů.',
    ],
    'light_fighter' => [
        'title' => 'Lehký stíhač',
        'description' => 'Lehký stíhač je obratná loď, která je k nalezení na téměr každé planetě. Náklady nejsou příliš vysoké, nicméně síla štítů a nákladová kapacita jsou velmi nízké.',
        'description_long' => 'Toto je první bojová loď, kterou všichni císaři postaví. Lehká stíhačka je obratná loď, ale zranitelná, když je sama. V masovém počtu se mohou stát velkou hrozbou pro každou říši. Jako první doprovázejí malé i velké náklady na nepřátelské planety s menší obranou.',
    ],
    'heavy_fighter' => [
        'title' => 'Těžký stíhač',
        'description' => 'Tento stíhač je lépe obrněný a má větší útočnou sílu než lehký stíhač.',
        'description_long' => 'Při vývoji těžké stíhačky dospěli vědci do bodu, kdy konvenční pohony již neposkytovaly dostatečný výkon. Aby se loď optimálně pohybovala, byl poprvé použit impulsní pohon. To zvýšilo náklady, ale také otevřelo nové možnosti. Použitím tohoto pohonu zbylo více energie pro zbraně a štíty; navíc byly pro tuto novou rodinu stíhaček použity vysoce kvalitní materiály. S těmito změnami představuje těžký stíhač novou éru v lodní technologii a je základem pro technologii křižníků. 

Těžký stíhač, o něco větší než lehký stíhač, má tlustší trupy, které poskytují větší ochranu a silnější zbraně.',
    ],
    'cruiser' => [
        'title' => 'Křižník',
        'description' => 'Křižníky jsou obrněné téměř třikrát více než těžké stíhačky a mají více než dvojnásobnou palebnou sílu. Navíc jsou velmi rychlé.',
        'description_long' => 'S rozvojem těžkého laseru a iontového děla se lehké a těžké stíhačky setkaly s alarmujícím počtem porážek, které se s každým náletem zvyšovaly. Navzdory mnoha modifikacím, změnám síly zbraní a pancéřování se nepodařilo zvýšit dostatečně rychle, aby účinně čelila těmto novým obranným opatřením. Proto bylo rozhodnuto postavit novou třídu lodí, která kombinovala více pancíře a větší palebnou sílu. Jako výsledek let výzkumu a vývoje se zrodil Cruiser. 

Křižníky jsou pancéřovány téměř třikrát než těžké stíhačky a mají více než dvojnásobnou palebnou sílu než jakákoli existující bojová loď. Mají také rychlosti, které daleko předčí jakoukoli kosmickou loď, která kdy byla vyrobena. Téměř jedno století vládly vesmíru křižníky. S vývojem Gaussových děl a plazmových věží však jejich převaha skončila. Proti stíhacím skupinám se používají dodnes, ale ne tak převážně jako dříve.',
    ],
    'battle_ship' => [
        'title' => 'Bitevní loď',
        'description' => 'Bitevní lodě tvoří páteř letky. Jejich těžká děla, vysoká rychlost a rozsáhlý nákladový prostor přiměly jejich protivníky brát je vážně.',
        'description_long' => 'Jakmile se ukázalo, že křižník ztrácí půdu pod nohama kvůli rostoucímu počtu obranných struktur, kterým čelil, a se ztrátami lodí na misích na nepřijatelných úrovních bylo rozhodnuto postavit loď, která by mohla čelit stejnému typu obranných struktur s co nejmenšími ztrátami. Po rozsáhlém vývoji se zrodila Bitevní loď. Bitevní loď, postavená tak, aby vydržela i ty největší bitvy, nabízí velké nákladové prostory, těžká děla a vysokou rychlost hyperpohonu. Jakmile byl vyvinut, nakonec se ukázalo, že je páteří každé nájezdní flotily císařů.',
    ],
    'battlecruiser' => [
        'title' => 'Bitevní křižník',
        'description' => 'Největší specializací bitevního křižníku je zachycování nepřátelských letek.',
        'description_long' => 'Tato loď je jednou z nejpokročilejších bojových lodí, jaké kdy byly vyvinuty, a je obzvláště smrtící, pokud jde o ničení útočících flotil. S vylepšenými laserovými děly na palubě a pokročilým Hyperprostorovým motorem je Battlecruiser vážnou silou, se kterou se musíte vypořádat při jakémkoli útoku. Kvůli konstrukci lodi a jejímu velkému zbraňovému systému musel být nákladný prostor vyříznut, ale to je kompenzováno nižší spotřebou paliva.',
    ],
    'bomber' => [
        'title' => 'Bombardér',
        'description' => 'Bombardér byl speciálně vyvinut pro ničení planetárních obranných systémů světa.',
        'description_long' => 'V průběhu staletí, jak se obrana začínala zvětšovat a důmyslně doplňovat, se flotily začaly ničit znepokojivou rychlostí. Bylo rozhodnuto, že je zapotřebí nová loď k prolomení obrany, aby byly zajištěny maximální výsledky. Po letech výzkumu a vývoje vznikl Bomber. 

Pomocí laserem naváděného zaměřovacího zařízení a plazmových bomb vyhledává a ničí jakýkoli obranný mechanismus, který najde. Jakmile je hyperprostorový pohon vyvinut na úroveň 8, je Bomber dodatečně vybaven hyperprostorovým motorem a může létat vyšší rychlostí.',
    ],
    'destroyer' => [
        'title' => 'Ničitel',
        'description' => 'Ničitel je král válečných lodí.',
        'description_long' => 'Destroyer je výsledkem let práce a vývoje. S vývojem Deathstars bylo rozhodnuto, že k obraně proti tak masivní zbrani je potřeba třída lodí. Díky vylepšeným naváděcím senzorům, multifalangovým iontovým kanónům, Gaussovým kanónům a plazmovým věžím se Destroyer ukázal být jednou z nejděsivějších lodí vytvořených. 

Protože je torpédoborec velmi velký, jeho manévrovatelnost je značně omezená, což z něj dělá spíše bitevní stanici než bojovou loď. Nedostatek manévrovatelnosti je kompenzován jeho pouhou palebnou silou, ale jeho stavba a provoz také stojí značné množství deuteria.',
    ],
    'deathstar' => [
        'title' => 'Hvězda smrti',
        'description' => 'Zničující síla hvězdy smrti je dosud nepřekonaná.',
        'description_long' => 'Deathstar je nejmocnější loď, která kdy byla vytvořena. Tato loď velikosti měsíce je jedinou lodí, kterou lze vidět pouhým okem na zemi. Ve chvíli, kdy si toho všimnete, je bohužel pozdě cokoliv dělat. 

Tato masivní loď, vyzbrojená gigantickým gravitonovým kanónem, nejpokročilejším zbraňovým systémem, jaký byl kdy ve vesmíru vytvořen, má nejen schopnost ničit celé flotily a obranu, ale má také schopnost ničit celé měsíce. Pouze nejvyspělejší říše mají schopnost postavit loď této mamutí velikosti.',
    ],
    'reaper' => [
        'title' => 'Rozparovač',
        'description' => 'Reaper je výkonná bojová loď specializovaná na agresivní nájezdy a sklizeň trosek.',
        'description_long' => 'Reaper představuje vrchol vojenského inženýrství třídy General. Toto těžce vyzbrojené plavidlo bylo navrženo pro velitele, kteří oceňují jak bojovou zdatnost, tak taktickou flexibilitu. Zatímco jeho primární role je boj, Reaper má zesílené nákladové prostory, které mu umožňují sklízet pole trosek po bitvě. Jeho pokročilé systémy zaměřování a těžké brnění z něj dělají impozantního protivníka, zatímco jeho dvouúčelový design znamená, že může vytvářet i těžit z krveprolití na bojišti. Loď je vybavena špičkovou zbrojní technologií a dokáže obstát i proti mnohem větším plavidlům.',
    ],
    'rocket_launcher' => [
        'title' => 'Raketomet',
        'description' => 'Raketomet je obranné opatření, které je vhodné pro svou jednoduchost a pro výtečný poměr cena/výkon.',
        'description_long' => 'Vaše první základní obranná linie. Jedná se o jednoduchá pozemní odpalovací zařízení, která odpalují konvenční střely s hlavicí na útočící nepřátelské cíle. Vzhledem k tomu, že jsou levné na konstrukci a není potřeba žádný výzkum, jsou velmi vhodné pro obranu nájezdů, ale ztrácejí účinnost při obraně před útoky většího rozsahu. Jakmile začnete stavět na pokročilejších obranných zbraňových systémech, raketomety se stanou jednoduchým krmivem, které umožní vašim škodlivějším zbraním způsobovat větší poškození po delší dobu. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'light_laser' => [
        'title' => 'Lehký laser',
        'description' => 'Koncentrovaná palba fotonů na cíl může způsobit znatelně větší poškození než obyčejné střelné zbraně.',
        'description_long' => 'Jak se technologie vyvíjela a vznikaly sofistikovanější lodě, bylo rozhodnuto, že k odvrácení útoků je zapotřebí silnější linie obrany. Jak laserová technologie pokročila, byla navržena nová zbraň, která poskytuje další úroveň obrany. Světelné lasery jsou jednoduché pozemní zbraně, které využívají speciální zaměřovací systémy ke sledování nepřítele a vystřelují vysoce intenzivní laser určený k proříznutí trupu cíle. Aby byly nákladově efektivní, byly vybaveny vylepšeným systémem stínění, avšak strukturální integrita je stejná jako u raketometu. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'heavy_laser' => [
        'title' => 'Těžký laser',
        'description' => 'Těžký laser je logickým stupněm vývoje lehkého laseru.',
        'description_long' => 'Těžký laser je praktická, vylepšená verze lehkého laseru. Je vyváženější než světelný laser s vylepšeným složením slitiny, využívá silnější, hustěji zabalené paprsky a ještě lepší palubní zaměřovací systémy. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'gauss_cannon' => [
        'title' => 'Gaussův kanón',
        'description' => 'Gaussův kanón pálí vysokou rychlostí tuny těžké projektily.',
        'description_long' => 'Po dlouhou dobu byly projektilové zbraně považovány za zastaralé v důsledku moderní termonukleární a energetické technologie a díky vývoji hyperpohonu a vylepšenému pancéřování. To bylo do té doby, než přesná energetická technologie, která ho kdysi zestárla, mu pomohla znovu dosáhnout zavedené pozice. 
Gaussovo dělo je velká verze urychlovače částic. Extrémně těžké střely jsou urychlovány obrovskou elektromagnetickou silou a mají úsťovou rychlost, díky které špína obklopující střelu hoří na obloze. Tato zbraň je při výstřelu tak silná, že vytváří sonický třesk. Moderní brnění a štíty jen stěží odolávají síle, často je cíl zcela proražen silou střely. Obranné struktury se deaktivují, jakmile jsou příliš poškozeny. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'ion_cannon' => [
        'title' => 'Iontový kanón',
        'description' => 'Iontový kanón pálí nepřetržitý svazek zrychlených iontů, které zasaženým objektům způsobují značná poškození.',
        'description_long' => 'Iontové dělo je zbraň, která vystřeluje paprsky iontů (kladně nebo záporně nabité částice). Iontové dělo je ve skutečnosti typ částicového děla; pouze použité částice jsou ionizovány. Díky svým elektrickým nábojům mají také potenciál vyřadit elektronická zařízení a cokoli jiného, ​​co má elektrický nebo podobný zdroj energie, pomocí jevu známého jako elektromagnetický puls (EMP efekt). Díky vysoce vylepšenému systému stínění děl poskytuje toto dělo zlepšenou ochranu pro vaše větší, ničivější obranné zbraně. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'plasma_turret' => [
        'title' => 'Plasmová věž',
        'description' => 'Plasmové věže uvolňují energii o síle sluneční erupce, které v ničivosti předčí i Ničitele.',
        'description_long' => 'Plazmová věž, jeden z nejpokročilejších obranných zbraňových systémů, jaký byl kdy vyvinut, využívá velký palivový článek jaderného reaktoru k pohonu elektromagnetického urychlovače, který vystřeluje puls neboli toroid plazmy. Během provozu se plazmová věž nejprve uzamkne na cíl a zahájí proces palby. V jádru věží se vytváří plazmová koule přehříváním a stlačováním plynů, které je zbavují jejich iontů. Jakmile je plyn přehřátý, stlačený a vytvořena plazmová koule, je poté vložen do elektromagnetického urychlovače, který je nabuzen. Po plném nabití se aktivuje urychlovač, což má za následek vypuštění plazmové koule extrémně vysokou rychlostí k zamýšlenému cíli. Z pohledu cíle je blížící se namodralá koule plazmy působivá, ale jakmile zasáhne, způsobí okamžitou zkázu. 

Obranná zařízení se deaktivují, jakmile jsou příliš silně poškozena. Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'small_shield_dome' => [
        'title' => 'Malý planetární štít',
        'description' => 'Malý planetární štít chrání celou planetu polem, které dokáže absorbovat obrovské množství energie.',
        'description_long' => 'Kolonizace nových světů přinesla nové nebezpečí, vesmírný odpad. Velký asteroid by mohl snadno zničit svět a všechny obyvatele. Pokrok v technologii stínění poskytl vědcům způsob, jak vyvinout štít, který by chránil celou planetu nejen před vesmírným odpadem, ale, jak bylo zjištěno, před nepřátelským útokem. Vytvořením velkého elektromagnetického pole kolem planety byl vesmírný odpad, který by za normálních okolností planetu zničil, odkloněn a útoky nepřátelských Impérií byly zmařeny. První generátory byly velké a štít poskytoval střední ochranu, ale později se zjistilo, že malé štíty neposkytují ochranu před útoky většího rozsahu. Malá štítová kopule byla předehrou k silnějšímu a pokročilejšímu planetárnímu stínícímu systému, který měl přijít. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'large_shield_dome' => [
        'title' => 'Velký planetární štít',
        'description' => 'Toto vylepšení malého obranného štítu může významně pomoci odolat útokům.',
        'description_long' => 'Velký štítový dóm je dalším krokem v rozvoji planetárních štítů, je výsledkem let práce na vylepšení Malé štítové kupole. Velké kopule jsou vyrobeny tak, aby vydržely větší příval nepřátelské palby tím, že poskytují elektromagnetické pole s vyšší energií, a poskytují delší dobu ochrany před zhroucením. 

Po bitvě je až 70% šance, že selhaná obranná zařízení mohou být vrácena k použití.',
    ],
    'anti_ballistic_missile' => [
        'title' => 'Antibalistické rakety',
        'description' => 'Antibalistické rakety ničí útočící meziplanetární rakety',
        'description_long' => 'Antibalistické střely (ABM) jsou vaší jedinou obrannou linií, když na vaši planetu nebo měsíc zaútočí meziplanetární střely (IPM). Když je detekováno vypuštění IPM, tyto střely se automaticky aktivují, zpracují odpalovací kód ve svých letových počítačích, zaměří se na příchozí IPM a vystřelí k zachycení. Během letu je cílový IPM neustále sledován a jsou aplikovány korekce kurzu, dokud ABM nedosáhne cíle a nezničí útočící IPM. Každý ABM zničí jeden příchozí IPM.',
    ],
    'interplanetary_missile' => [
        'title' => 'Meziplanetární rakety',
        'description' => 'Meziplanetární rakety ničí nepřátelskou obranu.',
        'description_long' => 'Meziplanetární střely (IPM) jsou vaší útočnou zbraní ke zničení obrany vašeho cíle. Pomocí nejmodernější sledovací technologie zaměří každá střela na určitý počet obranných zařízení, aby je zničila. Osazené antihmotovou bombou dodávají ničivou sílu tak silnou, že zničené štíty a obranu nelze opravit. Jediný způsob, jak čelit těmto střelám, jsou ABM.',
    ],
    'kraken' => [
        'title' => 'KRAKEN',
        'description' => 'Zkracuje dobu výstavby budov aktuálně ve výstavbě o <b>:duration</b>.',
    ],
    'detroid' => [
        'title' => 'DETROID',
        'description' => 'Zkracuje dobu výstavby aktuálních smluv s loděnicemi o <b>:duration</b>.',
    ],
    'newtron' => [
        'title' => 'NEWTRON',
        'description' => 'Zkracuje dobu výzkumu u veškerého aktuálně probíhajícího výzkumu o <b>:duration</b>.',
    ],
];
