<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sr (OGame: yu)
 * Source   : resources/lang/en/t_overview.php
 * Built    : 2026-04-12T16:16:20+00:00
 */

return [
    'overview' => 'Pregled',
    'temperature' => 'Температура',
    'position' => 'Положај',
];
